version: '3.7'
services:
  proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
    ports:
    - target: 4180
      published: 8080
      protocol: tcp
      mode: host
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
      
      OAUTH2_PROXY_UPSTREAMS: http://membership:8080/
      OAUTH2_PROXY_REDIRECT_URL: http://localhost:8080/oauth2/callback 
     
      OAUTH2_PROXY_SKIP_AUTH_ROUTES: 'GET=^/favicon.ico$$'
     
      OAUTH2_PROXY_FORCE_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      
      OAUTH2_PROXY_PROVIDER: oidc 
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: auth0
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://synshop.auth0.com/
       
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_COOKIE_SECURE: 'false'
      OAUTH2_PROXY_COOKIE_REFRESH: 5m
      OAUTH2_PROXY_COOKIE_NAME: SESSION
            
      # You can put the following values in a .env file KEY=VAL format
      OAUTH2_PROXY_CLIENT_ID: ${OAUTH2_PROXY_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
      OAUTH2_SHOW_DEBUG_ON_ERROR: 'true'
  membership:
    image: membership
    build:
      context: .
      dockerfile: Dockerfile
      

